---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: internal-spring-petclinic
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb
#     service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
#     service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
# spec:
#   selector:
#     app: spring-petclinic
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: external-spring-petclinic
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: spring-petclinic
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
